version: "3.6"

services:
  tests:
    image: openjdk:8-jdk-slim
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    command: ./gradlew build